send-mail-after-registering-a-mentor
linchpino/linchpino-core pull request #62
Opened 2024-06-06 17:37 UTC by SMSaeedi

2024-06-08 12:08 UTC, m-tilab requested changes

2024-06-08 12:08 UTC, m-tilab commented on src/main/kotlin/com/linchpino/core/service/AccountService.kt
> +import java.util.*
Please, prevent the use of STAR in the import statement

2024-06-08 12:08 UTC, m-tilab commented on src/main/kotlin/com/linchpino/core/service/AccountService.kt
> +            registeredMentor.firstName!!,
Are you confident that the 'registeredMentor.firstName' variable is not null? because if it is null, an exception will be thrown.
Please Prevent use !! to learn more please read: https://chatgpt.com/share/25551ba8-991b-4ce7-86f1-be1536b772c7

2024-06-08 15:01 UTC, SMSaeedi commented on src/main/kotlin/com/linchpino/core/service/AccountService.kt
> +            registeredMentor.firstName!!,
The Account request params are required, so even if the **name** and/or **family** and/or **email** are sent empty the exception raises on request level and prevent the further process, thus, when it comes to sending an email name, family and email are for sure filled up.

2024-06-08 15:07 UTC, SMSaeedi commented on src/main/kotlin/com/linchpino/core/service/AccountService.kt
> +import java.util.*
Done!

2024-06-08 16:24 UTC, SMSaeedi commented on src/main/kotlin/com/linchpino/core/service/AccountService.kt
> +            registeredMentor.firstName!!,
@m-tilab done! let is used now to avoid KotlinNullPointerException

2024-06-09 12:32 UTC, m-tilab approved these changes

2024-06-09 12:32 UTC, merged